# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinManager' do
  pod 'Firebase/Auth'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
end
